### ISSUE TITLE
Hi @carreraprogrammer ,

### ISSUE THREAD

**Issue by carreraprogrammer** [carreraprogrammer/school#5]
Hi @carreraprogrammer , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://camo.githubusercontent.com/59fa9d95c18dbd5a8e47490a9e4b48393f569685410f3c78d4d83a9764fa1392/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966" />

## Highlights :heavy_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x] Gitflow is used correctly :white_check_mark: 
- [x] Descriptive pull request title and summary :white_check_mark: 
- [x] Good descriptive commit messages :white_check_mark: 

## Required Changes ♻️ 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

_Originally posted by @Felix45 in https://github.com/carreraprogrammer/school/pull/4#pullrequestreview-1294017031_

**Comment by carreraprogrammer** [comment]
Microverse asked me for an issue link, but this is my pull request in order to follow the process https://github.com/carreraprogrammer/school/pull/4

**Comment by ridwanediallo** [comment]
Hi @carreraprogrammer , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: 

You have submitted an issue instead of a pull request. Please make sure to submit the PR link or could you clear tell the reason why you submited an issue link?

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by carreraprogrammer** [comment]
Hello @ridwanediallo, I don't know if it is an error in the platform, but on the send page, they didn't accept the link of my pull request and said that the format should have an issue form. I tried a lot of times but it was not possible, and it is the first time that it happens
